- dataset_prefix: /brandon/evilevo/evo2/preprocess/ncbi_viruses_homo_sapiens_uint8_byte-level_train
  dataset_split: train
  dataset_weight: 1.0
- dataset_prefix: /brandon/evilevo/evo2/preprocess/ncbi_viruses_homo_sapiens_uint8_byte-level_val
  dataset_split: validation
  dataset_weight: 1.0
- dataset_prefix: /brandon/evilevo/evo2/preprocess/ncbi_viruses_homo_sapiens_uint8_byte-level_test
  dataset_split: test
  dataset_weight: 1.0